app:
  features:
    sample-data: false
    watermark: ${WATERMARK:true}
  pdf:
    server-side: true
    pool-size: 1

langchain4j:
  open-ai:
    chat-model:
      api-key: ${API_KEY}
      model-name: gemini-3.1-flash-lite
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
